### ISSUE TITLE
TypeError: github.GitHub is not a constructor

### ISSUE THREAD

**Issue by cryptix** [mdecoleman/pr-branch-name#4]
I just tried to use this and got this:

```
Error: TypeError: github.GitHub is not a constructor
Error: github.GitHub is not a constructor
```

Sadly no line number but I guess it's this line:

https://github.com/mdecoleman/pr-branch-name/blob/7ff2bbfd59781596d6af3a36670bd9edcd948cdd/src/main.js#L15

**Comment by mdecoleman** [comment]
@cryptix I have pushed a new version if you use `uses: mdecoleman/pr-branch-name@1.2.0` it should fix your issue
