### ISSUE TITLE
`mdecoleman/pr-branch-name@v1` does not work

### ISSUE THREAD

**Issue by PhilipVinc** [mdecoleman/pr-branch-name#6]
Specifying `    - uses: mdecoleman/pr-branch-name@v1`
as would be useful to get security updates without breakages would be great.

However this does not work with error
```
Error: Unable to resolve action `mdecoleman/pr-branch-name@v1`, unable to find version `v1`
```

**Comment by mdecoleman** [comment]
@PhilipVinc i have pushed a new release that should fix your issue.

If you switch to `uses: mdecoleman/pr-branch-name@1.2.0` it should work for you

**Comment by mdecoleman** [comment]
Closing this as the latest version runs as intended
