### ISSUE TITLE
Set Environment and node version warning in github actions.

### ISSUE THREAD

**Issue by kvernon** [mdecoleman/pr-branch-name#9]
currently when running this actions, which is very cool (and thanks for making it), currently shows this warning because google is updating what they're allowing for node versions.

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Also, it references this project to need an update to node js:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mdecoleman/pr-branch-name, *************************************

**Comment by mdecoleman** [comment]
Hi @kvernon i've committed a new version to fix your issue above. Thank you for the detailed issue and the relevant links.

I have set the default node version of the action to `node16` now and also bumped the core actions lib to the new version.

If you use version `2.0.0` it should be good to go let me know if you get any problems.

**Comment by kvernon** [comment]
Thank you kindly for updating your project/ library. I'm looking forward to using it new glammed up version! 

Cheers,
Kelly
